### ISSUE TITLE
Can't run `app/console server:run`

### ISSUE THREAD

**Issue by willdurand** [beberlei/symfony-minimal-distribution#4]
Hi Benjamin!

It looks like running `app/console server:run` does not work as expected. Obviously, it does not load any env variables.. Running `php -S ...` works fine though.

William

**Comment by kbond** [comment]
I'm also having this issue when trying to use Dotenv

**Comment by willdurand** [comment]
@kbond solution is to make `Dotenv` mutable:

```
Dotenv::makeMutable();
```
