### ISSUE TITLE
Debug::enable()

### ISSUE THREAD

**Issue by kbond** [beberlei/symfony-minimal-distribution#5]
In the standard dist, we have `Debug::enable()` in the front controller.

Should this be included in this dist's front controller? Something like:

``` php
if ((bool) $_SERVER['SYMFONY_DEBUG']) {
    \Symfony\Component\Debug\Debug::enable();
}
```

?

**Comment by willdurand** [comment]
:+1:

**Comment by kbond** [comment]
Closing as stale.
